version: "3.7"

services:
  mongodb:
    image: mongo
    networks:
      - mongo_net
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - /home/hsb/mongodb:/data/db # 몽고 db 컨테이너의 데이터는 /data/db안에 있다.
    

  mongo-express:
    image: mongo-express
    networks:
      - mongo_net
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
  
  mongo_flask:
    build:
      context: ./docker_app_flask
      dockerfile: Dockerfile
    image: mongo_flask:1.0
    container_name: mongo_flask
    hostname: myservice
    environment:
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=password
      - MONGO_SERVER=mongodb
    ports:
      - 8050:5000
    networks:
      - mongo_net
    depends_on:
      - mongodb
    

networks:
  mongo_net:
    driver: bridge